version: "2.3"

services:
    postgres:
        container_name: service-postgres
        image: postgres:12
        environment:
          - POSTGRES_DB=pg_service_template_db-1
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
        ports:
          - 5432
        volumes:
          - ./postgresql/schemas:/docker-entrypoint-initdb.d
          - ./.pgdata:/var/lib/postgresql/data
        networks:
          - postgres

    pg_service_template-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-base-ci:latest
        privileged: true
        environment:
          - POSTGRES_DB=pg_service_template_db-1
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/pg_service_template/.ccache
          - CORES_DIR=/cores
        volumes:
          - .:/pg_service_template:rw
          - ./third_party/userver/scripts/docker/:/tools:ro
          - ${TC_CORES_DIR:-./.cores}:/cores:rw
        ports:
          - 8080:8080
        working_dir: /pg_service_template
        entrypoint:
          - /tools/run_as_user.sh
        depends_on:
          - postgres
        networks:
          - postgres

networks:
    postgres:
        driver: bridge
